Repository Automattic/super-cool-ad-inserter-plugin, pull requests merged in 2021-11, with the labels that each got.

#65 feat: block-insertion
  docs/adding-ads.md
  docs/configuration.md
  docs/display-settings.md
  inc/scaip-metaboxes.php
  inc/scaip-settings.php
  inc/scaip-shortcode-inserter.php
Labels: [Status] Needs Review

#70 fix: execute filter before block rendering
  inc/scaip-shortcode-inserter.php
Labels: [Status] Needs Review

#74 feat: filter blocks to be counted on ad insertion
  inc/scaip-shortcode-inserter.php
Labels: [Status] Needs Review

#75 fix: serialize block, allow empty innerHTML and html paragraphs
  inc/scaip-shortcode-inserter.php
Labels: [Status] Needs Review, Next Release

#78 fix: insertion logic
  .circleci/config.yml
  inc/scaip-shortcode-inserter.php
Labels: [Status] Approved, Next Release

#81 Release Nov 18
  .circleci/config.yml
  CHANGELOG.md
  inc/scaip-settings.php
  inc/scaip-shortcode-inserter.php
  inc/scaip-shortcode.php
  package-lock.json
  package.json
  super-cool-ad-inserter-plugin.php
  tests/inc/test-scaip-shortcode.php
Labels: [Status] Needs Review
